version: "3.8"
#Para servidor Linux
services:
  # exemplo início 8 #
  php8-fpm:
    image: testephp
    networks:
      - net_swarm
    volumes:
      - ./php/app-consumer-kafka:/var/www
      - ./database/sqlite:/database
      # - ./Supervisord/php8/:/etc/supervisord.d
      # - ./Php/php.ini-production:/usr/local/etc/php/php.ini
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.1"
          memory: 20M
      restart_policy:
        condition: on-failure
  # exemplo fim #

networks:
  net_swarm:
    external: true
    name: net_swarm
